/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    docSidebar: [
    'why-gravity',
    'core-concepts',
    'app-scenario',
    {
      type: 'category',
      label: 'Use Case Examples',
      items: [
        {
          type: "autogenerated",
          dirName: "use-case-ex",
        }
      ],
    },
    'quickstart',
    {
      type: 'category',
      label: 'Installation Guide',
      // items: [
      //   'install-guide/requirements',
      //   'install-guide/env',
      //   'install-guide/install-k8',
      //   'install-guide/deployment',
      //   'install-guide/atomic-guide',
      // ],
      items: [
        {
          type: "autogenerated",
          dirName: "install-guide",
        }
      ]
    },
    {
      type: 'category',
      label: 'Configurations',
      items: [
          {
              type: 'category',
              label: 'Adapter Configurations',
              // items:[
              //     'config/adapter-config/psql',
              //     'config/adapter-config/mssql',
              //     'config/adapter-config/oracle',
              //     'config/adapter-config/mysql',
              //     'config/adapter-config/mongodb',
              //     'config/adapter-config/informix',
              //     'config/adapter-config/ogg',
              // ],
              items: [
                  {
                      type: "autogenerated",
                      dirName: "config/adapter-config",
                  }
              ]
          },
          'config/dispatcher-config',
          'config/atomic-modules',
          'config/ldap',
      ],
    },
    {
      type: 'category',
      label: 'Atomic',
      // items: [
      //     'atomic/atomic-guide',
      //     'atomic/atomic-batch-feature',
      // ],
      items: [
        {
          type: "autogenerated",
          dirName: "atomic",
        }
      ]
    },
    'cli',
    ],
    apiSidebar: [
        'api/general',
        {
          type: 'category',
          label: 'Gravity-SDK',
          items: [
            'api/sdk/overview',
          ],
        },
        'api/graviton',

    ],
    // faqSidebar: [
    //     'faq/general',
    //     'faq/gravity-cli',
    //     'faq/gravity-portal',
    //     'faq/troubleshooting',
    // ]
    faqSidebar: [
      {
        type: 'autogenerated',
        dirName: 'faq',
      }
    ]





  // You can create another sidebar manually if needed
    //
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;

